name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t glen-python-app .

      - name: Run Docker image (test)
        run: docker run --rm glen-python-app

